name: playground_dart_polymer
description: Playground for Dart and Polymer
environment:
  sdk: '>=1.8.0 <2.0.0'
dependencies:
  polymer: '>=0.15.1 <0.16.0'
#  core_elements: ">=0.3.0 <0.4.0"
  paper_elements: ">=0.4.0 <0.5.0"
dev_dependencies:
  unittest: '>=0.10.0 <0.11.0'
transformers:
- polymer:
    entry_points:
      - web/stopwatch/index.html
      - web/editor/index.html